westerveltco/django-twc-project

Justfile
copied from `django-twc-package`, for easy releasing so I don't forget something
=> add new `create-release-pr` command

CHANGELOG.md, src/django_twc_project/{{ module_name }}/settings.py.jinja, src/django_twc_project/{{ module_name }}/users/migrations/0001_initial.py
=> revert `DEFAULT_AUTO_FIELD` to `AutoField`

CHANGELOG.md, src/django_twc_project/pyproject.toml.jinja
- add missing `bumpver` update to tests
- add coverage settings
- add `djLint` ignore rule
- add `boto3` and `botocore` to `mypy` ignores
- add additional `ruff` config
- format
=> adjust `pyproject.toml`

CHANGELOG.md, src/django_twc_project/requirements.in.jinja, src/django_twc_project/{{ module_name }}/settings.py.jinja
=> add `django-q-registry`

CHANGELOG.md, src/django_twc_project/requirements.in.jinja
=> add `django-twc-toolbox`

CHANGELOG.md, src/django_twc_project/requirements.in.jinja, src/django_twc_project/{{ module_name }}/settings.py.jinja
=> add `django-simple-nav`

CHANGELOG.md, src/django_twc_project/.github/workflows/deploy.yml.jinja, src/django_twc_project/.github/workflows/test.yml.jinja
- bump all gha steps
- update CHANGELOG
=> bump gha steps

src/django_twc_project/.github/workflows/deploy.yml.jinja, src/django_twc_project/.github/workflows/test.yml.jinja
=> add `westerveltco/setup-ci-action` composite workflow

CHANGELOG.md, src/django_twc_project/.env.example.jinja, src/django_twc_project/Justfile.jinja
=> fix `postgres_uri_scheme` in template

.github/workflows/examples.yml, .github/workflows/test.yml, .pre-commit-config.yaml, CHANGELOG.md, copier.yml
=> bump default Python version to 3.12

CHANGELOG.md, src/django_twc_project/Dockerfile.jinja
=> add missing tzdata system package to dev Dockerfile stage

CHANGELOG.md, src/django_twc_project/.just/copier.just, src/django_twc_project/.just/django.just, src/django_twc_project/.just/docker.just, src/django_twc_project/.just/documentation.just, src/django_twc_project/.just/node.just, src/django_twc_project/.just/postgres.just, src/django_twc_project/.just/project.just, src/django_twc_project/.just/python.just.jinja, src/django_twc_project/Justfile.jinja
=> refactor template `Justfile` to use `just` modules

CHANGELOG.md, src/django_twc_project/.github/CODEOWNERS
=> add Data Analytics GH team to `CODEOWNERS` for PRs with migrations

CHANGELOG.md, src/django_twc_project/.just/postgres.just
- account for potential postgis uri scheme
- fix `dump-prod` just module command call
closes #180
=> fix postgres `Justfile` commands

CHANGELOG.md, copier.yml, src/django_twc_project/{{ module_name }}/settings.py.jinja
=> add question for using Cloudflare R2 and adjust STORAGES setting

CHANGELOG.md, copier.yml
=> remove question about 1Password vault

CHANGELOG.md, copier.yml, mkdocs.yml
=> :books: Add placeholder mkdocs.yml

CHANGELOG.md, copier.yml
=> bump Django version options

CHANGELOG.md, src/django_twc_project/{{ module_name }}/users/admin.py
=> remove unneeded type ignore comment

CHANGELOG.md, copier.yml
=> bump default Tailwind CSS version to 3.4.6

src/django_twc_project/Justfile.jinja
if you run the `just` formatter, it does this anyway
=> adjust `dotenv-load` syntax in `Justfile`

CHANGELOG.md, src/django_twc_project/pyproject.toml.jinja, src/django_twc_project/{{ module_name }}/settings.py.jinja
=> move dev dependencies behind `DEBUG` check

CHANGELOG.md, src/django_twc_project/pyproject.toml.jinja
=> add `django-stubs-ext` as explicit dep

CHANGELOG.md, src/django_twc_project/.github/workflows/test.yml.jinja
=> change to `simplify` branch of `westerveltco/setup-ci-action`

CHANGELOG.md, copier.yml, src/django_twc_project/package.json.jinja, src/django_twc_project/pyproject.toml.jinja
=> add extras for ui and toolbox deps, add ui version

CHANGELOG.md, src/django_twc_project/.just/prod.just, src/django_twc_project/Justfile.jinja
=> add just module for interacting with production application

CHANGELOG.md, src/django_twc_project/.github/workflows/deploy.yml.jinja
=> disable deploying with depot in Fly
